# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBkggS7sum16BWkreNUDL0e4Yv4n-f4n

->Experiment with 5 lists in-built function, and post it to github.
"""

dit={"a":300, "b":400,"c":"onkar"}
dit.get("b")

dit["c"]

dit.pop("b")
dit

dit.copy()
dit

dit.clear()
dit